export interface CountryCode {
  code: string; // ISO alpha-2
  dial: string; // dial code with +
  nameAr: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "SY", dial: "+963", nameAr: "سوريا", flag: "" },
  { code: "TR", dial: "+90", nameAr: "تركيا", flag: "🇹🇷" },
  { code: "SA", dial: "+966", nameAr: "السعودية", flag: "🇸🇦" },
  { code: "AE", dial: "+971", nameAr: "الإمارات", flag: "🇦🇪" },
  { code: "EG", dial: "+20", nameAr: "مصر", flag: "🇪🇬" },
  { code: "JO", dial: "+962", nameAr: "الأردن", flag: "🇯🇴" },
  { code: "LB", dial: "+961", nameAr: "لبنان", flag: "🇱🇧" },
  { code: "IQ", dial: "+964", nameAr: "العراق", flag: "🇮🇶" },
  { code: "KW", dial: "+965", nameAr: "الكويت", flag: "🇰🇼" },
  { code: "QA", dial: "+974", nameAr: "قطر", flag: "🇶🇦" },
  { code: "BH", dial: "+973", nameAr: "البحرين", flag: "🇧🇭" },
  { code: "OM", dial: "+968", nameAr: "عُمان", flag: "🇴🇲" },
  { code: "YE", dial: "+967", nameAr: "اليمن", flag: "🇾🇪" },
  { code: "PS", dial: "+970", nameAr: "فلسطين", flag: "🇵🇸" },
  { code: "LY", dial: "+218", nameAr: "ليبيا", flag: "🇱🇾" },
  { code: "SD", dial: "+249", nameAr: "السودان", flag: "🇸🇩" },
  { code: "TN", dial: "+216", nameAr: "تونس", flag: "🇹🇳" },
  { code: "DZ", dial: "+213", nameAr: "الجزائر", flag: "🇩🇿" },
  { code: "MA", dial: "+212", nameAr: "المغرب", flag: "🇲🇦" },
  { code: "MR", dial: "+222", nameAr: "موريتانيا", flag: "🇲🇷" },
  { code: "SO", dial: "+252", nameAr: "الصومال", flag: "🇸🇴" },
  { code: "DJ", dial: "+253", nameAr: "جيبوتي", flag: "🇩🇯" },
  { code: "KM", dial: "+269", nameAr: "جزر القمر", flag: "🇰🇲" },
  { code: "DE", dial: "+49", nameAr: "ألمانيا", flag: "🇩🇪" },
  { code: "FR", dial: "+33", nameAr: "فرنسا", flag: "🇫🇷" },
  { code: "GB", dial: "+44", nameAr: "المملكة المتحدة", flag: "🇬🇧" },
  { code: "US", dial: "+1", nameAr: "الولايات المتحدة", flag: "🇺🇸" },
  { code: "CA", dial: "+1", nameAr: "كندا", flag: "🇨🇦" },
  { code: "NL", dial: "+31", nameAr: "هولندا", flag: "🇳🇱" },
  { code: "BE", dial: "+32", nameAr: "بلجيكا", flag: "🇧🇪" },
  { code: "SE", dial: "+46", nameAr: "السويد", flag: "🇸🇪" },
  { code: "NO", dial: "+47", nameAr: "النرويج", flag: "🇳🇴" },
  { code: "DK", dial: "+45", nameAr: "الدنمارك", flag: "🇩🇰" },
  { code: "FI", dial: "+358", nameAr: "فنلندا", flag: "🇫🇮" },
  { code: "AT", dial: "+43", nameAr: "النمسا", flag: "🇦🇹" },
  { code: "CH", dial: "+41", nameAr: "سويسرا", flag: "🇨🇭" },
  { code: "IT", dial: "+39", nameAr: "إيطاليا", flag: "🇮🇹" },
  { code: "ES", dial: "+34", nameAr: "إسبانيا", flag: "🇪🇸" },
  { code: "PT", dial: "+351", nameAr: "البرتغال", flag: "🇵🇹" },
  { code: "GR", dial: "+30", nameAr: "اليونان", flag: "🇬🇷" },
  { code: "PL", dial: "+48", nameAr: "بولندا", flag: "🇵🇱" },
  { code: "CZ", dial: "+420", nameAr: "التشيك", flag: "🇨🇿" },
  { code: "RO", dial: "+40", nameAr: "رومانيا", flag: "🇷🇴" },
  { code: "BG", dial: "+359", nameAr: "بلغاريا", flag: "🇧🇬" },
  { code: "HU", dial: "+36", nameAr: "هنغاريا", flag: "🇭🇺" },
  { code: "UA", dial: "+380", nameAr: "أوكرانيا", flag: "🇺🇦" },
  { code: "RU", dial: "+7", nameAr: "روسيا", flag: "🇷🇺" },
  { code: "IR", dial: "+98", nameAr: "إيران", flag: "🇮🇷" },
  { code: "IN", dial: "+91", nameAr: "الهند", flag: "🇮🇳" },
  { code: "PK", dial: "+92", nameAr: "باكستان", flag: "🇵🇰" },
  { code: "BD", dial: "+880", nameAr: "بنغلاديش", flag: "🇧🇩" },
  { code: "AF", dial: "+93", nameAr: "أفغانستان", flag: "🇦🇫" },
  { code: "CN", dial: "+86", nameAr: "الصين", flag: "🇨🇳" },
  { code: "JP", dial: "+81", nameAr: "اليابان", flag: "🇯🇵" },
  { code: "KR", dial: "+82", nameAr: "كوريا الجنوبية", flag: "🇰🇷" },
  { code: "MY", dial: "+60", nameAr: "ماليزيا", flag: "🇲🇾" },
  { code: "ID", dial: "+62", nameAr: "إندونيسيا", flag: "🇮🇩" },
  { code: "TH", dial: "+66", nameAr: "تايلاند", flag: "🇹🇭" },
  { code: "PH", dial: "+63", nameAr: "الفلبين", flag: "🇵🇭" },
  { code: "VN", dial: "+84", nameAr: "فيتنام", flag: "🇻🇳" },
  { code: "SG", dial: "+65", nameAr: "سنغافورة", flag: "🇸🇬" },
  { code: "AU", dial: "+61", nameAr: "أستراليا", flag: "🇦🇺" },
  { code: "NZ", dial: "+64", nameAr: "نيوزيلندا", flag: "🇳🇿" },
  { code: "BR", dial: "+55", nameAr: "البرازيل", flag: "🇧🇷" },
  { code: "AR", dial: "+54", nameAr: "الأرجنتين", flag: "🇦🇷" },
  { code: "MX", dial: "+52", nameAr: "المكسيك", flag: "🇲🇽" },
  { code: "CL", dial: "+56", nameAr: "تشيلي", flag: "🇨🇱" },
  { code: "CO", dial: "+57", nameAr: "كولومبيا", flag: "🇨🇴" },
  { code: "ZA", dial: "+27", nameAr: "جنوب أفريقيا", flag: "🇿🇦" },
  { code: "NG", dial: "+234", nameAr: "نيجيريا", flag: "🇳🇬" },
  { code: "KE", dial: "+254", nameAr: "كينيا", flag: "🇰🇪" },
  { code: "ET", dial: "+251", nameAr: "إثيوبيا", flag: "🇪🇹" },
  { code: "GH", dial: "+233", nameAr: "غانا", flag: "🇬🇭" },
  { code: "SN", dial: "+221", nameAr: "السنغال", flag: "🇸🇳" },
  { code: "AZ", dial: "+994", nameAr: "أذربيجان", flag: "🇦🇿" },
  { code: "GE", dial: "+995", nameAr: "جورجيا", flag: "🇬🇪" },
  { code: "AM", dial: "+374", nameAr: "أرمينيا", flag: "🇦🇲" },
  { code: "KZ", dial: "+7", nameAr: "كازاخستان", flag: "🇰🇿" },
  { code: "UZ", dial: "+998", nameAr: "أوزبكستان", flag: "🇺🇿" },
  { code: "IL", dial: "+972", nameAr: "إسرائيل", flag: "🇮🇱" },
  { code: "CY", dial: "+357", nameAr: "قبرص", flag: "🇨🇾" },
  { code: "MT", dial: "+356", nameAr: "مالطا", flag: "🇲🇹" },
  { code: "IE", dial: "+353", nameAr: "أيرلندا", flag: "🇮🇪" },
];

export const DEFAULT_COUNTRY = "SY";

export const findCountry = (code: string) =>
  COUNTRY_CODES.find((c) => c.code === code) ?? COUNTRY_CODES[0];
