project_id = "cflrdbkvpzzilazdufmh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-email-otp]
    verify_jwt = false
