project_id = "cflrdbkvpzzilazdufmh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.verify-email-otp]
    verify_jwt = false
  [functions.delete-own-account]
    verify_jwt = true
